### ISSUE TITLE
deleteItem exception

### ISSUE THREAD

**Issue by doc-rj-celltrak** [lesnitsky/flutter_localstorage#55]
In 3.0.4+7, calling deleteItem() crashes in flush() if there is no file (nothing has been written yet).

flutter: NoSuchMethodError: The method 'lock' was called on null.
Receiver: null
Tried calling: lock()
flutter: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DirUtils.flush (package:localstorage/src/directory/io.dart:46:25)
#2      LocalStorage._flush (package:localstorage/localstorage.dart:103:18)
#3      LocalStorage.deleteItem (package:localstorage/localstorage.dart:92:12)

**Comment by doc-rj-celltrak** [comment]
Hmmmm, we're seeing the issue with setItem() too, even though we are awaiting ready during initialization.

flutter: NoSuchMethodError: The method 'lock' was called on null.
Receiver: null
Tried calling: lock()
flutter: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DirUtils.flush (package:localstorage/src/directory/io.dart:46:25)
#2      LocalStorage._flush (package:localstorage/localstorage.dart:103:18)
#3      LocalStorage.setItem (package:localstorage/localstorage.dart:86:12)

===

final storage = LocalStorage('redux.json', cttPath);
await storage.ready;
...

**Comment by PerLycke** [comment]
Same issue here after updating from 3.0.3+6 to 3.0.4+7

**Comment by Stevensie95** [comment]
Try to change version from ^3.0.4+7 to ^3.0.4

**Comment by lesnitsky** [comment]
please check v3.0.5

**Comment by lesnitsky** [comment]
sorry for the inconvenience
